services:
  rabbitmq:
    image: 'rabbitmq:3-management'
    container_name: 'rabbitmq'
    ports:
      - '5672:5672'
      - '15672:15672'

  postgres:
    image: postgres:latest
    container_name: 'postgres'
    environment:
      - POSTGRES_USER=user
      - POSTGRES_PASSWORD=postgres
      - PGDATA=/var/lib/postgresql/data/
      - POSTGRES_DB=ecommerce
      - TZ=GMT-3
      - PGTZ=GMT-3
    ports:
      - '5432:5432'
    volumes:
      - ./init/tablespace_init.sql:/docker-entrypoint-initdb.d/tablespace_init.sql
      - db:/var/lib/postgresql/data/:rw


  redis:
    image: redislabs/redismod
    container_name: redis
    ports:
      - '6379:6379'

  redisinsight:
    image: redislabs/redisinsight:latest
    container_name: redisinsight
    ports:
      - '8001:8001'

  wiremock:
    image: wiremock/wiremock:3.3.1
    container_name: wiremock
    ports:
      - '9000:8080'
    environment:
      WIREMOCK_OPTIONS: '--verbose'
      TZ: GMT-3
    volumes:
      - ./mocks:/home/wiremock/:rw

volumes:
  db:
    driver: local