
server.port: 8080

spring:
  config:
    activate.on-profile: default
  application.name: ecommerce-receiver

  cloud:
    function:
      definition: autorizarVendaQueue
    stream:
      bindings:
        autorizarVendaQueue-out-0:
          destination: autorizar-venda-queue
          group: ${application.name}
          binder: rabbit
      binders:
        rabbit:
          type: rabbit
          environment:
            spring:
              rabbitmq:
                host: ${RABBITMQ_HOST:localhost}
                port: 5672
                username: ${RABBITMQ_USERNAME:guest}
                password: ${RABBITMQ_PASSWORD:guest}
                virtual-host: /

---
spring:
  config:
    activate.on-profile: test
  application.name: ecommerce-receiver

  cloud:
    function:
      definition: autorizar-venda-queue
